accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/like/", views.like, name="like"),
    path("index/", views.index, name="index"),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="images/", blank=True)
    price = models.PositiveIntegerField(max_length=50)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="articles"
    )

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="comments"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    content = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updaetd_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ["author", "like_users"]

articles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST


def index(request):
    return render(request, "articles/index.html")


def articles(request):
    articles = Article.objects.all().order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "articles/articles.html", context)


def article_detail(request, pk):
    print("detail")
    article = get_object_or_404(Article, pk=pk)
    context = {
        "article": article,
    }
    return render(request, "articles/article_detail.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect("articles:article_detail", article.pk)
    else:
        form = ArticleForm()
        print("else")

    context = {"form": form}
    return render(request, "articles/create.html", context)


@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if article.author == request.user:
        if request.method == "POST":
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect("articles:article_detail", article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        form = ArticleForm(instance=article)

    context = {
        "form": form,
        "article": article,
    }
    return render(request, "articles/update.html", context)


@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user.is_authenticated:
        if article.author == request.user:
            article = get_object_or_404(Article, pk=pk)
            article.delete()
    return redirect("articles:articles")


@require_POST
def like(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)  # 좋아요 취소
        else:
            article.like_users.add(request.user)  # 좋아요
        return redirect("articles:articles")
    return redirect("accounts:login")

articles/templates/articles/article_detail.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
<h2>{{ article.title }}</h2>

{% if user.is_authenticated and user.username == article.author.username %}
<a href="{% url 'users:profile' username=user.username %}" class="btn btn-white">작성자 : {{ article.author.username }}</a>
{% else %}
<a href="{% url 'users:profile' username=article.author.username %}" class="btn btn-white">작성자 : {{article.author.username }}</a>
{% endif %}

<br>
<br>

{% if article.image %}
<img src="{{ article.image.url }}" style="width: 500px; height: 300px;">
{% endif %}

<p>가격 : {{ article.price | intcomma }}</p>
<p>내용: {{ article.content }}</p>

<p>작성일시: {{ article.created_at }}</p>
<p>수정일시: {{ article.updated_at }}</p>

<a href="{% url 'articles:articles' %}">목록보기</a>

{% if user == article.author %}
<a href="{% url 'articles:update' article.pk %}">
    <button>수정하기</button>
</a>

<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
{% endif %}
{% endblock content %}

articles/templates/articles/articles.html
{% extends "base.html" %} 
{% load humanize %}


{% block content %}
  <h1>중고거래 게시판</h1>
  <div>
    {% if request.user.is_authenticated %}
      <button style="float: right;">
        <a href="{% url 'articles:create' %}">새로운 글작성</a>
      </button>
    {% else %}
      <a href="{% url 'accounts:login' %}">로그인하고 글 작성하기</a>
    {% endif %}
  </div>
  <br>
  <br>
  <br>
  <br>
  <div class="row row-cols-1 row-cols-md-3 g-4" >
    {% for article in articles %}
      <div class="col">
        <div class="card" >
          {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top" style="width: 400px; height: 200px">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'articles:article_detail' article.pk %}">
                <p>[{{ article.pk }}] {{ article.title }}</p>
                <p>가격 : {{ article.price | intcomma }}</p>
              </a>
            </h5>
            <p class="card-text">{{ article.content }}</p>
            <form action="{% url 'articles:like' article.pk %}" method="POST">
              {% csrf_token %}
              {% if request.user in article.like_users.all %}
                <input type="submit" value="❤️">
              {% else %}
                <input type="submit" value="🖤">
              {% endif %}
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock content %}

articles/templates/articles/create.html
{% extends "base.html" %} 
{% load humanize %}

{% block content %}
<h2>중고물품 작성하기</h2>

<form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="display: flex; flex-direction: column;">
        <br>
        <label for="id_title">제목:</label>
        <input type="text" name="title" id="id_title" size="50">
        <br>
        <br>
        <label for="id_content">내용:</label>
        {{ form.content }}
        <br>
        <label for="id_price">가격:</label>
        {{ form.price }}
        <br>
        <label for="id_image">물건 사진 업로드하기:</label>
        {{ form.image }}
        <br>
    </div>
    <button type="submit" style="display: flex; flex-direction: column;">저장</button>
</form>

<a href="{% url 'articles:articles' %}">목록으로</a>

{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 style="text-align: center;">Spartar Market</h1>

  <div class="background-image" id="market">
    <br>
    <br>
    <br>
    <br>
    <br>
    <img class="market" src="{% static 'articles/우리는 삽니다 좋은 장비를.png' %}">

  </div>

{% endblock content %}

articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}
<h2>게시글 수정하기</h2>

<form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">수정</button>
</form>

<a href="{% url 'articles:article_detail' article.pk %}">이전으로</a>
{% endblock content %}