articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/like/", views.like, name="like"),
    path("index/", views.index, name="index"),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

users/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


def users(request):
    return render(request, "users/users.html")

@login_required
def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username)
    article = member.like_articles.all()
    my_article = member.articles.all()
    context = {
        "member": member,
        "article": article,
        "my_article": my_article,
    }
    return render(request, "users/profile.html", context)


@require_POST
def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if member != request.user:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("users:profile", member.username)
    return redirect("accounts:login")

users/templates/users/profile.html
{% extends 'base.html' %}
{% load humanize %}
{% load static  %}
{% block content %}
<h2>{{ member.username }}님의 프로필 </h2>

{% if member.profile_image %}
        <img src="{{ member.profile_image.url }}" style="width: 500px; height: 500px;">
    {% else %}
        <img src="{% static 'articles\user.png' %}" style="width: 500px; height: 500px;">
    {% endif %}

<p>팔로워 수: {{ member.followers.count }}</p>
<p>팔로잉 수: {{ member.followings.count }}</p>
<p>가입일: {{ member.date_joined }}</p>
<p>최근 로그인 이력: {{ member.last_login }}</p>

{% if request.user != member %}
<form action="{% url 'users:follow' member.pk %}" method="POST">
    {% csrf_token %}
    {% if request.user in member.followers.all %}
    <input type="submit" value="언팔로우">
    {% else %}
    <input type="submit" value="팔로우">
    {% endif %}
</form>
{% endif %}

<br>
<br>
<br>
<br>
<br>
<br>
<h2>찜한 상품 목록</h2>
<div class="row row-cols-1 row-cols-md-3 g-4" >
    {% for article in article %}
      <div class="col">
        <div class="card" >
          {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top" style="width: 400px; height: 200px">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'articles:article_detail' article.pk %}">
                <p>[{{ article.pk }}] {{ article.title }}</p>
                <p>가격 : {{ article.price | intcomma }}</p>
              </a>
            </h5>
            <p class="card-text">{{ article.content }}</p>
            <form action="{% url 'articles:like' article.pk %}" method="POST">
              {% csrf_token %}
              {% if request.user in article.like_users.all %}
                <input type="submit" value="❤️">
              {% else %}
                <input type="submit" value="🖤">
              {% endif %}
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

<br>
<br>
<br>
<br>
<br>
<br>
<h2>내가 등록한 상품</h2>
<div class="row row-cols-1 row-cols-md-3 g-4" >
    {% for article in my_article %}
      <div class="col">
        <div class="card" >
          {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top" style="width: 400px; height: 200px">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'articles:article_detail' article.pk %}">
                <p>[{{ article.pk }}] {{ article.title }}</p>
                <p>가격 : {{ article.price | intcomma }}</p>
              </a>
            </h5>
            <p class="card-text">{{ article.content }}</p>
            <form action="{% url 'articles:like' article.pk %}" method="POST">
              {% csrf_token %}
              {% if request.user in article.like_users.all %}
                <input type="submit" value="❤️">
              {% else %}
                <input type="submit" value="🖤">
              {% endif %}
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

<a href="/index/">홈으로 돌아가기</a>

{% endblock content %}

users/templates/users/users.html
{% extends 'base.html' %}

{% block content %}
  <h1> Users Page </h1>

  <br>
  <a href="{% url 'index' %}">INDEX로 가기</a>
{% endblock content %}