accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/like/", views.like, name="like"),
    path("index/", views.index, name="index"),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <title>MY DJANGO</title>

    {% block head %}{% endblock head %}
  </head>
  <style>

    .market {
      position: absolute;
      width: 800px;
      height: 580px;
      top: 55%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: -1;
    }

  </style>

  <body>
    <header class="p-3 text-bg-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-black text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
              <use xlink:href="#bootstrap"></use>
            </svg>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li>
              <a href="{%url 'articles:index' %}" class="nav-link px-2 text-secondary">Home</a>
            </li>
            <li>
              <a href="{%url 'articles:articles' %}" class="nav-link px-2 text-black">Board</a>
            </li>
          </ul>

          {% if user.is_authenticated %}
            <div class="text-end">

              <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="로그아웃"></input>

              </form>

              <form action="{% url 'accounts:delete' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="회원탈퇴"></input>

              </form>

              <a href="{% url 'users:profile' username=user.username %}" class="btn btn-white">{{ user }}님</a>

              <a href="{% url 'accounts:update' %}" class="btn btn-white">정보수정하기</a>

            </div>

          {% else %}
            <div class="text-end">
              <button type="button" class="btn btn-outline-light me-2">
                <a href="{% url 'accounts:login' %}">로그인</a>
              </button>
              <button type="button" class="btn btn-warning">
                <a href="{% url 'accounts:signup' %}">회원가입</a>
              </button>
            </div>
          {% endif %}
        </div>
      </div>
    </header>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="container">
      {% block content %}{% endblock content %}
    </div>

  </div>

</body>

</html>